apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
    {{- include "vault-kubeconfig-external-secret.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvMountPath | quote }}
      version: {{ .Values.vault.kvVersion | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vault.auth.tokenSecretName }}
          key: {{ .Values.vault.auth.tokenSecretKey }}
