{{- if .Values.vault.auth.createTokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.auth.tokenSecretName }}
  labels:
    {{- include "vault-kubeconfig-external-secret.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.vault.auth.tokenSecretKey }}: {{ required "vault.auth.token is required when vault.auth.createTokenSecret=true" .Values.vault.auth.token | quote }}
{{- end }}
