services:
  vault:
    image: hashicorp/vault:1.20
    container_name: vault-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:8200:8200"
      - "127.0.0.1:8201:8201"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault.hcl:/vault/config/vault.hcl:ro
      - ./data:/vault/data
    command: vault server -config=/vault/config/vault.hcl
    environment:
      VAULT_ADDR: http://127.0.0.1:8200